version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: "todo-postgres"
      POSTGRES_PASSWORD: "todo-postgres"
      POSTGRES_DB: todo-postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d